In [22]:
import pandas as pd
weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}
df = pd.DataFrame(weather_data)
df = pd.read_csv("weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [26]:
df.replace(-99999, np.nan, inplace=True)
df.fillna(df.mean(numeric_only=True), inplace=True)
df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017         31.4        7.0  Sunny
2  1/3/2017         28.0        5.4   Snow
3  1/4/2017         31.4        7.0      0
4  1/5/2017         32.0        5.4   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

In [27]:
df.shape # rows, columns = df.shape

(7, 4)

In [28]:
df.head() # df.head(3)

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017         31.4        7.0  Sunny
2  1/3/2017         28.0        5.4   Snow
3  1/4/2017         31.4        7.0      0
4  1/5/2017         32.0        5.4   Rain

In [29]:
df.tail() # df.tail(2)

        day  temperature  windspeed  event
2  1/3/2017         28.0        5.4   Snow
3  1/4/2017         31.4        7.0      0
4  1/5/2017         32.0        5.4   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

In [30]:
df[1:3]

        day  temperature  windspeed  event
1  1/2/2017         31.4        7.0  Sunny
2  1/3/2017         28.0        5.4   Snow

In [31]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [32]:
df['day'] # or df.day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
6    1/6/2017
Name: day, dtype: object

In [33]:
type(df['day'])

pandas.core.series.Series

In [34]:
df[['day', 'temperature']]

        day  temperature
0  1/1/2017         32.0
1  1/2/2017         31.4
2  1/3/2017         28.0
3  1/4/2017         31.4
4  1/5/2017         32.0
5  1/6/2017         31.0
6  1/6/2017         34.0

In [35]:
df['temperature'].max()

34.0

In [36]:
df[df['temperature']>32]

        day  temperature  windspeed event
6  1/6/2017         34.0        5.0     0

In [37]:
df['day'][df['temperature'] == df['temperature'].max()] # Kinda doing SQL in pandas

6    1/6/2017
Name: day, dtype: object

In [38]:
df[df['temperature'] == df['temperature'].max()] # Kinda doing SQL in pandas

        day  temperature  windspeed event
6  1/6/2017         34.0        5.0     0

In [39]:
print(df['temperature'].std())

1.788854381999832

In [40]:
df['event'].max() # But mean() won't work since data type is string

'Sunny'

In [41]:
df.describe()

       temperature  windspeed
count     7.000000   7.000000
mean     31.400000   5.400000
std       1.788854   1.693123
min      28.000000   2.000000
25%      31.200000   5.200000
50%      31.400000   5.400000
75%      32.000000   6.500000
max      34.000000   7.000000

In [42]:
df.set_index('day')

          temperature  windspeed  event
day
1/1/2017         32.0        6.0   Rain
1/2/2017         31.4        7.0  Sunny
1/3/2017         28.0        5.4   Snow
1/4/2017         31.4        7.0      0
1/5/2017         32.0        5.4   Rain
1/6/2017         31.0        2.0  Sunny
1/6/2017         34.0        5.0      0

In [43]:
df.set_index('day', inplace=True)

In [44]:
df.index

Index(['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017',
       '1/6/2017'],
      dtype='object', name='day')

In [45]:
df.loc['1/2/2017']

temperature     31.4
windspeed        7.0
event          Sunny
Name: 1/2/2017, dtype: object

In [46]:
df.reset_index(inplace=True)
df.head()

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017         31.4        7.0  Sunny
2  1/3/2017         28.0        5.4   Snow
3  1/4/2017         31.4        7.0      0
4  1/5/2017         32.0        5.4   Rain

In [47]:
df.set_index('event',inplace=True) # this is kind of building a hash map using event as a key
df

            day  temperature  windspeed
event
Rain   1/1/2017         32.0        6.0
Sunny  1/2/2017         31.4        7.0
Snow   1/3/2017         28.0        5.4
0      1/4/2017         31.4        7.0
Rain   1/5/2017         32.0        5.4
Sunny  1/6/2017         31.0        2.0
0      1/6/2017         34.0        5.0

In [50]:
df.loc['Snow']

day            1/3/2017
temperature        28.0
windspeed           5.4
Name: Snow, dtype: object

In [51]:
import pandas as pd

pakistani_weather = pd.DataFrame({
    "city": ["karachi","lahore","peshawar"],
    "temperature": [32,45,30],
    "humidity": [80, 60, 78]
})
pakistani_weather

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78

In [52]:
us_weather = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68, 65, 75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [53]:
df = pd.concat([pakistani_weather, us_weather])
df

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [54]:
df = pd.concat([pakistani_weather, us_weather], ignore_index=True)
df

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78
3  new york           21        68
4   chicago           14        65
5   orlando           35        75

In [55]:
df = pd.concat([pakistani_weather, us_weather], keys=["pakistan", "us"])
df

                city  temperature  humidity
pakistan 0   karachi           32        80
         1    lahore           45        60
         2  peshawar           30        78
us       0  new york           21        68
         1   chicago           14        65
         2   orlando           35        75

In [56]:
df.loc["us"]

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [57]:
df.loc["pakistan"]

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78

In [58]:
temperature_df = pd.DataFrame({
    "city": ["karachi","lahore","peshawar"],
    "temperature": [32,45,30],
}, index=[0,1,2])
temperature_df

       city  temperature
0   karachi           32
1    lahore           45
2  peshawar           30

In [59]:
windspeed_df = pd.DataFrame({
    "city": ["lahore","karachi"],
    "windspeed": [7,12],
}, index=[1,0])
windspeed_df

      city  windspeed
1   lahore          7
0  karachi         12

In [60]:
df = pd.concat([temperature_df, windspeed_df], axis=1)
df

       city  temperature     city  windspeed
0   karachi           32  karachi       12.0
1    lahore           45   lahore        7.0
2  peshawar           30      NaN        NaN

In [61]:
s = pd.Series(["Humid","Dry","Rain"], name="event")
s

0    Humid
1      Dry
2     Rain
Name: event, dtype: object

In [62]:
df = pd.concat([temperature_df,s],axis=1)
df

       city  temperature  event
0   karachi           32  Humid
1    lahore           45    Dry
2  peshawar           30   Rain

In [63]:
import pandas as pd
df = pd.read_csv("weather_by_cities.csv")
df

         day      city  temperature  windspeed   event
0   1/1/2024  new york           32          6    Rain
1   1/2/2024  new york           36          7   Sunny
2   1/3/2024  new york           28         12    Snow
3   1/4/2024  new york           33          7   Sunny
4   1/1/2024     dubai           90          5   Sunny
5   1/2/2024     dubai           85         12     Fog
6   1/3/2024     dubai           87         15     Fog
7   1/4/2024     dubai           92          5    Rain
8   1/1/2024     paris           45         20   Sunny
9   1/2/2024     paris           50         13  Cloudy
10  1/3/2024     paris           54          8  Cloudy
11  1/4/2024     paris           42         10  Cloudy

In [64]:
g = df.groupby("city")
g

In [65]:
for city, data in g:
    print("city:",city)
    print("\n")
    print("data:",data)

city: dubai


data:         day   city  temperature  windspeed  event
4  1/1/2024  dubai           90          5  Sunny
5  1/2/2024  dubai           85         12    Fog
6  1/3/2024  dubai           87         15    Fog
7  1/4/2024  dubai           92          5   Rain
city: new york


data:         day      city  temperature  windspeed  event
0  1/1/2024  new york           32          6   Rain
1  1/2/2024  new york           36          7  Sunny
2  1/3/2024  new york           28         12   Snow
3  1/4/2024  new york           33          7  Sunny
city: paris


data:          day   city  temperature  windspeed   event
8   1/1/2024  paris           45         20   Sunny
9   1/2/2024  paris           50         13  Cloudy
10  1/3/2024  paris           54          8  Cloudy
11  1/4/2024  paris           42         10  Cloudy

In [66]:
g.get_group('paris')

         day   city  temperature  windspeed   event
8   1/1/2024  paris           45         20   Sunny
9   1/2/2024  paris           50         13  Cloudy
10  1/3/2024  paris           54          8  Cloudy
11  1/4/2024  paris           42         10  Cloudy

In [67]:
g.min()

               day  temperature  windspeed   event
city
dubai     1/1/2024           85          5     Fog
new york  1/1/2024           28          6    Rain
paris     1/1/2024           42          8  Cloudy

In [68]:

g.mean(numeric_only=True)

          temperature  windspeed
city
dubai           88.50       9.25
new york        32.25       8.00
paris           47.75      12.75

In [69]:
g.min()

               day  temperature  windspeed   event
city
dubai     1/1/2024           85          5     Fog
new york  1/1/2024           28          6    Rain
paris     1/1/2024           42          8  Cloudy

In [70]:
g.describe()

         temperature                                                   \
               count   mean       std   min    25%   50%    75%   max
city
dubai            4.0  88.50  3.109126  85.0  86.50  88.5  90.50  92.0
new york         4.0  32.25  3.304038  28.0  31.00  32.5  33.75  36.0
paris            4.0  47.75  5.315073  42.0  44.25  47.5  51.00  54.0

         windspeed
             count   mean       std  min   25%   50%    75%   max
city
dubai          4.0   9.25  5.057997  5.0  5.00   8.5  12.75  15.0
new york       4.0   8.00  2.708013  6.0  6.75   7.0   8.25  12.0
paris          4.0  12.75  5.251984  8.0  9.50  11.5  14.75  20.0

In [71]:
g.size()

city
dubai       4
new york    4
paris       4
dtype: int64

In [72]:
import pandas as pd
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
})
df1

       city  temperature
0  new york           21
1   chicago           14
2   orlando           35

In [73]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","orlando"],
    "humidity": [65,68,75],
})
df2

       city  humidity
0   chicago        65
1  new york        68
2   orlando        75

In [74]:
df3 = pd.merge(df1, df2, on="city")
df3

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [75]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando", "baltimore"],
    "temperature": [21,14,35, 38],
})
df1

        city  temperature
0   new york           21
1    chicago           14
2    orlando           35
3  baltimore           38

In [76]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","san diego"],
    "humidity": [65,68,71],
})
df2

        city  humidity
0    chicago        65
1   new york        68
2  san diego        71

In [77]:
df3=pd.merge(df1,df2,on="city",how="inner")
df3

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65

In [78]:
df3=pd.merge(df1,df2,on="city",how="outer")
df3

        city  temperature  humidity
0  baltimore         38.0       NaN
1    chicago         14.0      65.0
2   new york         21.0      68.0
3    orlando         35.0       NaN
4  san diego          NaN      71.0

In [79]:
df3=pd.merge(df1,df2,on="city",how="left")
df3

        city  temperature  humidity
0   new york           21      68.0
1    chicago           14      65.0
2    orlando           35       NaN
3  baltimore           38       NaN

In [80]:
df3=pd.merge(df1,df2,on="city",how="right")
df3

        city  temperature  humidity
0    chicago         14.0        65
1   new york         21.0        68
2  san diego          NaN        71

In [81]:
df3=pd.merge(df1,df2,on="city",how="outer",indicator=True)
df3

        city  temperature  humidity      _merge
0  baltimore         38.0       NaN   left_only
1    chicago         14.0      65.0        both
2   new york         21.0      68.0        both
3    orlando         35.0       NaN   left_only
4  san diego          NaN      71.0  right_only

In [82]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando", "baltimore"],
    "temperature": [21,14,35,38],
    "humidity": [65,68,71, 75]
})
df1

        city  temperature  humidity
0   new york           21        65
1    chicago           14        68
2    orlando           35        71
3  baltimore           38        75

In [83]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","san diego"],
    "temperature": [21,14,35],
    "humidity": [65,68,71]
})
df2

        city  temperature  humidity
0    chicago           21        65
1   new york           14        68
2  san diego           35        71

In [84]:
df3= pd.merge(df1,df2,on="city",how="outer", suffixes=('_first','_second'))
df3

,city,temperature_first,humidity_first,temperature_second,humidity_second
0,baltimore,38.0,75.0,NaN,NaN
1,chicago,14.0,68.0,21.0,65.0
2,new york,21.0,65.0,14.0,68.0
3,orlando,35.0,71.0,NaN,NaN
4,san diego,NaN,NaN,35.0,71.0

In [85]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
})
df1.set_index('city',inplace=True)
df1

          temperature
city
new york           21
chicago            14
orlando            35

In [86]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","orlando"],
    "humidity": [65,68,75],
})
df2.set_index('city',inplace=True)
df2

          humidity
city
chicago         65
new york        68
orlando         75

In [88]:
import pandas as pd
import numpy as np
df = pd.read_csv("weather.csv")
df

       date      city  temperature  humidity
0  5/1/2024  new york           65        56
1  5/2/2024  new york           66        58
2  5/3/2024  new york           68        60
3  5/1/2024     dubai           75        80
4  5/2/2024     dubai           78        83
5  5/3/2024     dubai           82        85
6  5/1/2024   beijing           80        26
7  5/2/2024   beijing           77        30
8  5/3/2024   beijing           79        35

In [89]:
df.pivot(index='city',columns='date')

         temperature                   humidity
date        5/1/2024 5/2/2024 5/3/2024 5/1/2024 5/2/2024 5/3/2024
city
beijing           80       77       79       26       30       35
dubai             75       78       82       80       83       85
new york          65       66       68       56       58       60

In [90]:
df.pivot(index='city',columns='date',values="humidity")

date      5/1/2024  5/2/2024  5/3/2024
city
beijing         26        30        35
dubai           80        83        85
new york        56        58        60

In [91]:
df.pivot(index='date',columns='city')

         temperature                humidity
city         beijing dubai new york  beijing dubai new york
date
5/1/2024          80    75       65       26    80       56
5/2/2024          77    78       66       30    83       58
5/3/2024          79    82       68       35    85       60

In [92]:

df.groupby('city')['humidity'].mean()

city
beijing     30.333333
dubai       82.666667
new york    58.000000
Name: humidity, dtype: float64

In [93]:
import pandas as pd
import numpy as np
df = pd.read_csv("weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [95]:
df[['temperature', 'windspeed']] = df[['temperature', 'windspeed']].mask(df[['temperature', 'windspeed']] < 0, np.nan)
df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

In [96]:
df['event'] = df['event'].replace(0, np.nan)
df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

In [98]:
df[['temperature', 'windspeed']] = df[['temperature', 'windspeed']].mask(df[['temperature', 'windspeed']] < 0, np.nan)
df['event'] = df['event'].replace(0, np.nan)
df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

In [99]:
print(df['event'].unique())
print(df['event'].apply(type))

['Rain' 'Sunny' 'Snow' '0']
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
Name: event, dtype: object

In [100]:
df['event'] = df['event'].replace(['0', 0], np.nan)
df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0    NaN